### ISSUE TITLE
Selection of long text passages yields no results

### ISSUE THREAD

**Issue by schloett** [EEXCESS/gdocs-plugin#38] opened 2015-09-30 10:08 UTC
When selecting a longer piece of text, the recommender does not return any results. I assume this is due to the selection being sent as a single keyword and hence an AND-connected query is generated. In general, this behavior is fine for me, but maybe a hint that explains why there are no results might be helpful for the user? Another alternative might be to extract noun phrases from the selection and use only those as query (or a similar approach).

**Comment by chseifert** [comment] 2015-10-27 09:27
Current strategy for the deployment - leave it as it is (see detailed comment in https://github.com/EEXCESS/gdocs-plugin/issues/35). 
Due to the time constraints I see logging as the more important issue.

**Comment by chseifert** [comment] 2015-10-27 09:37
Duplicate of https://github.com/EEXCESS/gdocs-plugin/issues/20

**Comment by chseifert** [comment] 2015-11-19 12:50
Results returned now for long queries.

**Closed as completed by chseifert** 2015-11-19 12:50 UTC
Labels: duplicate, question
